### ISSUE TITLE
Include stress-ng

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/waggle_image#7]
I think we should include stress-ng in the Waggle image for debugging purposes. (More generally, we should think about any debugging tools we use but don't get included.)

**Comment by MuffinSpawn** [comment]
Moving to the development repo...

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #16](https://github.com/waggle-sensor/development/issues/16) via [**ZenHub**](https://www.zenhub.com/)
