### ISSUE TITLE
Guest node doesn't mount boot partition automatically?

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/waggle_image#9]
I noticed that when `waggle_init.sh` ran, it complained that the boot partition was not mounted at `/media/boot` and then gave up. Do we intend to mount this automatically or do we intend to have the script mount it?

**Comment by MuffinSpawn** [comment]
Moving to the development branch...

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #17](https://github.com/waggle-sensor/development/issues/17) via [**ZenHub**](https://www.zenhub.com/)
